name:                mini-IOTasks
version:             0.1.1.0
github:              "githubuser/mini-IOTasks"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mini-IOTasks#readme>

dependencies:
- ansi-terminal
- base >= 4.7 && < 5
- constraints
- containers
- deriving-compat
- express
- extra
- mtl
- parsec
- pretty
- QuickCheck
- stm
- type-match
- z3

ghc-options:
- -Wall
- -Wno-name-shadowing
- -fdefer-typed-holes

library:
  source-dirs: src

tests:
  mini-IOTasks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -O2
    dependencies:
    - mini-IOTasks
    - hspec
    - monad-loops

benchmarks:
  hangman-benchmark:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -O2
    dependencies:
    - mini-IOTasks
    - criterion
