name:                IOTest
version:             0.0.2.0
github:              "owestphal/IOTest"
license:             BSD3
author:              "Oliver Westphal"
maintainer:          "oliver.westphal@uni-due.de"
copyright:           "2018 Oliver Westphal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/owestphal/IOTest#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- transformers
- containers
- recursion-schemes

library:
  source-dirs: src
  ghc-options:
  - -Wall

tests:
  IOTest-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IOTest
    - hspec
