name:                IOTasks
version:             2.2.0
github:              "fmidue/IOTasks"
license:             BSD3
author:              "Oliver Westphal"
maintainer:          "oliver.westphal@uni-due.de"
copyright:           "2023 Oliver Westphal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fmidue/IOTasks#readme>

dependencies:
- ansi-terminal
- async
- base >= 4.7 && < 5
- containers
- deriving-compat
- express
- extra
- mtl
- parsec
- pretty
- QuickCheck
- stm
- type-match
- z3

ghc-options:
- -Wall
- -Wmissing-export-lists
- -Wno-name-shadowing
- -fdefer-typed-holes

library:
  source-dirs: src
  other-modules:
    - Test.IOTasks.Internal.Output
    - Test.IOTasks.Internal.OutputPattern
    - Test.IOTasks.Internal.Overflow
    - Test.IOTasks.Internal.Specification
    - Test.IOTasks.Internal.SpecificationGenerator
    - Test.IOTasks.Internal.Term
    - Test.IOTasks.Internal.ValueSet

tests:
  IOTasks-test:
    main:                Spec.hs
    source-dirs:         [test, examples]
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - IOTasks
    - hspec
    - monad-loops
