resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/28.yaml

packages:
- .

extra-deps:
- git: https://github.com/IagoAbal/haskell-z3
  commit: 7e2a3e0977f277b9ed39ad182287317d2b819476
- git: https://github.com/owestphal/type-match
  commit: e5c0d104032d7e6ea147009669cbb95f3291b7bb

system-ghc: true
