resolver: lts-14.22

packages:
- IOTasks
- transparent-terms
- dynamic-environment

extra-deps:
- quickcheck-transformer-0.3.1
- pretty-tree-0.1.0.0
- holmes-0.3.2.0
- hashable-1.3.1.0
- primitive-0.7.1.0
