resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/6.yaml

packages:
- .

extra-deps:
- git: https://github.com/IagoAbal/haskell-z3
  commit: 6368e451e45359563106da7e917f6594453c5161
- git: https://github.com/owestphal/type-match
  commit: e5c0d104032d7e6ea147009669cbb95f3291b7bb
