name:                transparent-terms
version:             0.0.1.0
github:              "owestphal/IOTasks"
license:             BSD3
author:              "Oliver Westphal"
maintainer:          "oliver.westphal@uni-due.de"
copyright:           "2020 Oliver Westphal"

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Reflection

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/owestphal/IOTasks#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- dynamic-environment
- pretty-tree

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fdefer-typed-holes
  exposed-modules:
  - Data.Term
  - Data.Term.Class
  - Data.Term.ITerm
  - Data.Term.ATerm
  - Data.Term.Liftable
  - Data.Term.Liftable.Prelude
  - Data.Term.AST
  - Data.Term.Typed.AST
