name: Haskell CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Stack
      id: cache-stack-unix
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ubuntu-latest-stack-home-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: |
        set -ex
        stack --no-terminal --install-ghc test --bench --only-dependencies
        set +ex

    - name: Build
      run: |
        set -ex
        stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
        set +ex
